### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by ghaith99** [mattlisiv/newsapi-python#22]
When I run:
api.get_everything(q='bitcoin')

I get 
api.get_everything(q='bitcoin')
Traceback (most recent call last):

  File "<ipython-input-132-a9702e361f42>", line 1, in <module>
    api.get_everything(q='bitcoin')

  File "C:\Users\LapLap\Anaconda3\envs\fluffy\lib\site-packages\newsapi\newsapi_client.py", line 248, in get_everything
    r = requests.get(const.EVERYTHING_URL, auth=self.auth, timeout=30, params=payload)

  File "C:\Users\LapLap\Anaconda3\envs\fluffy\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)

  File "C:\Users\LapLap\Anaconda3\envs\fluffy\lib\site-packages\requests\api.py", line 57, in request
    with sessions.Session() as session:

  File "C:\Users\LapLap\Anaconda3\envs\fluffy\lib\site-packages\requests\sessions.py", line 386, in __init__
    self.mount('https://', HTTPAdapter())

  File "C:\Users\LapLap\Anaconda3\envs\fluffy\lib\site-packages\requests\adapters.py", line 120, in __init__
    super(HTTPAdapter, self).__init__()

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by mattlisiv** [comment]
Hi @ghaith99 ,

I can't seem to recreate this issue.

How is it that you are initializing your client?

Thanks,
Matt

**Comment by r0f1** [comment]
Hi, I get the same issue as described.
I tried the following piece of code:

```
import requests
url = ('https://newsapi.org/v2/top-headlines?'
       'country=us&'
       'apiKey=MY_API_KEY')
response = requests.get(url)
print(response.json())
```
